/**
 * Short human-readable descriptions for each BitShares operation type,
 * keyed by operation ID. Used as tooltip text on the Network Fees page.
 * Mirrors the operation IDs in `opTypes.js`.
 */
const opDescriptions = {
  0: "Send any asset from your account to another account.",
  1: "Place a limit order on the decentralized exchange to buy or sell an asset at a specific price.",
  2: "Cancel an existing limit order, returning the unsold funds to your account.",
  3: "Borrow a smartcoin by locking up collateral at (or above) the required maintenance collateral ratio.",
  4: "Generated when a limit or call order is matched; records which orders were filled. Cannot be submitted directly.",
  5: "Register a new account on the chain. Premium names fund referrers and the lifetime referrer.",
  6: "Update an account's owner/active authorities, options or signing keys.",
  7: "Add or remove accounts from an asset's whitelist or blacklist.",
  8: "Upgrade an account to annual or lifetime membership, unlocking fee rebates and referral earnings.",
  9: "Transfer full ownership of an account to another account.",
  10: "Create a new user-issued asset with its own symbol, precision and permissions.",
  11: "Update an asset's issuer, description, permissions or other settings.",
  12: "Adjust smartcoin parameters such as feeds, settlement price and margin requirements.",
  13: "Add or remove approved feed producers for a smartcoin.",
  14: "Issue a quantity of an asset you control to a chosen account.",
  15: "Burn (destroy) an amount of an asset you hold, permanently reducing the supply.",
  16: "Deposit core asset into an asset's fee pool so fees paid in that asset can be converted to core asset.",
  17: "Request forced settlement of a smartcoin position at the settlement price.",
  18: "Globally settle a smartcoin at a given price (requires the global_settle permission).",
  19: "Publish a new price feed for a smartcoin (feed producers only).",
  20: "Register a witness candidate so they can be voted onto the block production roster.",
  21: "Update a witness's block signing key, URL or fee schedule vote.",
  22: "Propose a transaction for one or more accounts to approve and execute together.",
  23: "Add or update your approval of an existing proposal.",
  24: "Delete a proposal you created that has not yet been executed or expired.",
  25: "Grant another account permission to withdraw a limited amount from your account per period.",
  26: "Modify an existing withdrawal permission's limits or time window.",
  27: "Claim funds made available by a withdrawal permission within its validity period.",
  28: "Remove a withdrawal permission before it expires naturally.",
  29: "Register a committee member candidate eligible to vote on chain parameters.",
  30: "Update a committee member's URL or voting options.",
  31: "Committee-approved change of global blockchain parameters such as fees and block size.",
  32: "Create a vesting balance, typically used for worker pay or cashback setup.",
  33: "Withdraw matured funds from a vesting balance.",
  34: "Create a worker proposal to receive a daily budget funded by the chain's worker pay reserve.",
  35: "Generic operation used by applications to store custom data or trigger contract-like behaviour.",
  36: "Verify preconditions (signatures, asset amounts) without transferring value. Fee is per condition.",
  37: "Claim funds held in an unspent balance (e.g. from genesis or old wallets) using its balance key/owner authority.",
  38: "Force a transfer from any account to an authority-controlled destination (committee powers only).",
  39: "Transfer into confidential blind balances, hiding amount and ownership.",
  40: "Move value between two confidential blind balances.",
  41: "Receive previously blinded funds back into your regular account balance.",
  42: "Cancel a pending forced settlement request for a smartcoin.",
  43: "Withdraw accumulated fees from an asset's accumulated fee balance back to the issuer.",
  44: "Distribute fees collected by a forward budget asset to its holders. Cannot be submitted directly.",
  45: "Place a bid for collateral in a globally settled smartcoin's collateral auction.",
  46: "Executed when a collateral auction concludes, paying out the winning bidder. Cannot be submitted directly.",
  47: "Claim funds from a smartcoin's settled or surplus collateral pool.",
  48: "Transfer issuance rights of an asset to a new issuing account.",
  49: "Create a hash-time locked contract: conditional transfer redeemable with a preimage, or refundable after expiry.",
  50: "Redeem an HTLC by providing the correct hash lock preimage.",
  51: "Generated when an HTLC is successfully redeemed. Cannot be submitted directly.",
  52: "Extend the expiration time of an existing HTLC.",
  53: "Return HTLC funds to the originator after the timeout expires.",
  54: "Create a custom (restricting) authority defining additional account permission rules.",
  55: "Update an existing custom authority's restrictions.",
  56: "Delete a custom authority.",
  57: "Create a governance ticket (e.g. a lockup tier) that boosts voting power.",
  58: "Update an existing governance ticket's details or target account.",
  59: "Create a liquidity pool holding two assets, enabling automated market making.",
  60: "Delete a liquidity pool whose balances are already empty.",
  61: "Deposit both pool assets in balanced proportion, receiving pool shares.",
  62: "Redeem pool shares for the underlying pair of assets.",
  63: "Swap one pool asset for the other at the current pool price.",
  64: "Create a SameT fund offering synthetic leveraged exposure to an underlying asset.",
  65: "Delete a SameT fund once all positions are closed.",
  66: "Update a SameT fund's parameters such as fees or ratios.",
  67: "Open a leveraged long or short position against a SameT fund.",
  68: "Close a SameT borrow position, settling profit or loss.",
  69: "Create a credit offer lending a specified asset under set collateral terms.",
  70: "Delete a credit offer that has no open deals.",
  71: "Update a credit offer's amount, rates or collateral requirements.",
  72: "Borrow from a credit offer by posting the required collateral.",
  73: "Repay an open credit deal, reclaiming the collateral.",
  74: "Generated when a credit deal expires unpaid and collateral is claimed. Cannot be submitted directly.",
  75: "Update a liquidity pool after creation (fees, owner or pool settings).",
  76: "Update terms of an existing credit deal between lender and borrower.",
  77: "Amend a resting limit order (price or amount) without cancelling it.",
};

export { opDescriptions };
